### ISSUE TITLE
metrical evaluation

### ISSUE THREAD

**Issue by liuxm117** [soubhiksanyal/now_evaluation#25]
hi, Is the non-metrical evaluation calculated by this code, and how to calculate the metrical evaluation

**Comment by TimoBolkart** [comment]
Hi, since the latest update, the code can compute both, metrical and non-metrical evaluation. For the metrical evaluation, just additionally pass the arguments `--metrical_evaluation True` and specify the unit of measurements of the reconstructed meshes with e.g., `--predicted_mesh_unit mm` for  unit mm.
